name: SONAR scan
on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main 
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: maven install 
      run : mvn install
    - name: maven compile 
      run : mvn compile
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.3.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  
  
    #  run: mvn -B verify sonar:sonar -Dsonar.projectKey=tanchiak_synk-vulnerable-javaapp   -Dsonar.organization=tanchiak -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN 
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
