name: Synk scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

#This is an EG of a multi job where needs is used run one job after another

jobs:
  synk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor